/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.birdirbir.admobrewarded;

import com.google.android.gms.ads.MobileAds;
import com.google.android.gms.ads.initialization.OnInitializationCompleteListener;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.kroll.common.TiConfig;

import java.util.HashMap;


@Kroll.module(name="Admobrewarded", id="net.birdirbir.admobrewarded")
public class AdmobrewardedModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "AdmobrewardedModule";
	private static final boolean DBG = TiConfig.LOGD;
	private static boolean initialized = false;

	public AdmobrewardedModule()
	{
		super();
	}


	@Kroll.method(runOnUiThread = true)
	public void initialize(KrollFunction callback){

		MobileAds.initialize(getActivity(), (OnInitializationCompleteListener) initializationStatus -> {
			initialized = true;
			if(callback != null){
				KrollDict data = new KrollDict();
				data.put("success", true);
				callback.callAsync(getKrollObject(), data);
			}
		});

	}

	@Kroll.method(runOnUiThread = true)
	public RewardedVideoProxy createAd(@SuppressWarnings("rawtypes") HashMap hm) {
		@SuppressWarnings("unchecked")
		KrollDict args = new KrollDict(hm);
		String adUnitID = args.getString("adUnitID");
		if(initialized){
			RewardedVideoProxy rewardedVideoProxy = new RewardedVideoProxy(adUnitID);
			return rewardedVideoProxy;
		}
		else{
			return null;
		}

	}


}

